name: Moose Dept.
favicon: null
layout_spectrum: 0.69191
typography_spectrum: 0.73255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060709'
    - '#2967b2'
    - '#7fb1ec'
    - '#f6dde3'
    - '#5d2d39'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
