name: Moose Dept.
favicon: null
layout_spectrum: 0.64877
typography_spectrum: 0.73255
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d7c7'
    - '#e9f6ff'
    - '#9a8862'
    - '#453929'
    - '#814d1d'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
